# Site settings
title: NXSDataWriter
email: jan.kotanski@desy.de
description: "NXSDataWriter"
# baseurl: ""
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown
# permalink: pretty

include: ['_sources', '_static', '_modules', '_images']